FROM matindocker/poly-lithic:base-latest

COPY deployment_config.yaml /opt/deployment/config.yaml
COPY env.json /opt/deployment/env.json
{% if model_source == "local" %}
COPY model_definition.py /opt/deployment/model_definition.py
{% endif %}

WORKDIR /opt/deployment

CMD ["pl", "run", "--publish", "-c", "config.yaml", "-e", "env.json"]
